"""Typed contracts for unified multimodal queries.

The first query contract intentionally models one high-value pattern:
exact vector seeding followed by two typed relation joins, per-seed top-k,
and bounded graph traversal.  The contract is backend-neutral so a future
optimizer can produce alternate physical plans without changing callers.
"""

from .algebra import (
    AlwaysTrue,
    AndPredicate,
    BindingRow,
    ComparisonPredicate,
    EdgeExistsPredicate,
    EdgeJoin,
    FieldRef,
    Filter,
    GroupTopK,
    InnerJoin,
    InSpacePredicate,
    LogicalOperator,
    NotPredicate,
    OrPredicate,
    Predicate,
    ProjectLimit,
    TopK,
    Traverse,
    UnitScan,
    VectorScan,
    evaluate_comparison,
    explain_logical_plan,
    metadata_equals,
    resolve_field_path,
)
from .vector_seeded import (
    OperatorExecutionMetrics,
    QueryExecutionMetrics,
    QueryStageBreakdown,
    QueryStageTimings,
    VectorSeededTraversalExecution,
    VectorSeededTraversalRow,
    VectorSeededTraversalSpec,
    format_query_log,
    render_query_diagram,
)

__all__ = [
    "AlwaysTrue",
    "AndPredicate",
    "BindingRow",
    "ComparisonPredicate",
    "EdgeExistsPredicate",
    "EdgeJoin",
    "FieldRef",
    "Filter",
    "GroupTopK",
    "InSpacePredicate",
    "InnerJoin",
    "LogicalOperator",
    "NotPredicate",
    "OperatorExecutionMetrics",
    "OrPredicate",
    "Predicate",
    "ProjectLimit",
    "QueryExecutionMetrics",
    "QueryStageBreakdown",
    "QueryStageTimings",
    "TopK",
    "Traverse",
    "UnitScan",
    "VectorScan",
    "VectorSeededTraversalExecution",
    "VectorSeededTraversalRow",
    "VectorSeededTraversalSpec",
    "evaluate_comparison",
    "explain_logical_plan",
    "format_query_log",
    "metadata_equals",
    "render_query_diagram",
    "resolve_field_path",
]
